### ISSUE TITLE
Can not run scripts/setup_sumo_osx.sh

### ISSUE THREAD

**Issue by xiaoToby** [flow-project/flow#572]
This is a: **Bug report**

**Describe the issue**

When I followed the instructions, I ran the command "scripts/setup_sumo_osx.sh"
 there is a error. 

```(flow) wlan-napt-003:flow xiaohongzhi$ scripts/setup_sumo_osx.sh
Installing system dependencies for SUMO
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and caskroom/cask).
No changes to formulae.

Warning: swig 4.0.0 is already installed and up-to-date
To reinstall 4.0.0, run `brew reinstall swig`
Warning: sdl 1.2.15_1 is already installed and up-to-date
To reinstall 1.2.15_1, run `brew reinstall sdl`
Warning: sdl_image 1.2.12_7 is already installed and up-to-date
To reinstall 1.2.12_7, run `brew reinstall sdl_image`
Warning: sdl_mixer 1.2.12_3 is already installed and up-to-date
To reinstall 1.2.12_3, run `brew reinstall sdl_mixer`
Warning: sdl_ttf 2.0.11_1 is already installed and up-to-date
To reinstall 2.0.11_1, run `brew reinstall sdl_ttf`
Warning: portmidi 217_2 is already installed and up-to-date
To reinstall 217_2, run `brew reinstall portmidi`
==> brew cask install Caskroom/cask/xquartz 
Warning: Cask 'xquartz' is already installed.

To re-install xquartz, run:
  brew cask reinstall xquartz
Warning: autoconf 2.69 is already installed and up-to-date
To reinstall 2.69, run `brew reinstall autoconf`
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
Warning: gdal 2.4.1_1 is already installed and up-to-date
To reinstall 2.4.1_1, run `brew reinstall gdal`
Warning: proj 6.1.0 is already installed and up-to-date
To reinstall 6.1.0, run `brew reinstall proj`
Warning: xerces-c 3.2.2 is already installed and up-to-date
To reinstall 3.2.2, run `brew reinstall xerces-c`
Warning: fox 1.6.56_1 is already installed and up-to-date
To reinstall 1.6.56_1, run `brew reinstall fox`
Installing sumo binaries
~/sumo_binaries/bin ~/flow
--2019-06-28 15:15:14--  https://akreidieh.s3.amazonaws.com/sumo/flow-0.3.1/binaries-mac.tar.xz
正在解析主机 akreidieh.s3.amazonaws.com (akreidieh.s3.amazonaws.com)... 52.219.116.98
正在连接 akreidieh.s3.amazonaws.com (akreidieh.s3.amazonaws.com)|52.219.116.98|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2019-06-28 15:15:14 错误 404：Not Found。

tar: Error opening archive: Failed to open 'binaries-mac.tar.xz'
rm: binaries-mac.tar.xz: No such file or directory
chmod: *: No such file or directory
~/flow
```

**Desktop (please complete the following information):**
 - OS: My os is macOS Mojave 10.14.5

**Comment by xiaoToby** [comment]
BTW,
I cannot download the sumo by following your instruction file.
I tried other ways to download sumo. https://github.com/DLR-TS/homebrew-sumo/blob/master/README.md

So i went on the instructions, actually i can ran "python examples/sumo/sugiyama.py".


Then i tried to download Aimsun, the aimsun is not free, right?
So i tried to download the trial version. Then i test my installation,
run "python examples/aimsun/sugiyama.py". The Aimsun window can be opened,
But there is nothing is running!!!

Ok, at least, there is no error.
Then i went to next. Download the rlib.
On the installing part, everything looks fine.
THen i test my installation.
Problem again!!!
the log is that:
(base) wlan-napt-003:flow xiaohongzhi$ source activate flow
(flow) wlan-napt-003:flow xiaohongzhi$ python examples/rllib/stabilizing_the_ring.py
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-28_15-35-37_73338/logs.
Waiting for redis server at 127.0.0.1:11257 to respond...
Waiting for redis server at 127.0.0.1:27753 to respond...
Starting the Plasma object store with 3.435973836 GB memory using /tmp.
I0628 15:35:38.073626 222512576 store.cc:994] Allowing the Plasma store to use up to 3.43597GB of memory.
I0628 15:35:38.076272 222512576 store.cc:1024] Starting object store with directory /tmp and huge page support disabled
Failed to start the UI, you may need to run 'pip install jupyter'.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 6.1/8.6 GB

Created LogSyncer for /Users/xiaohongzhi/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2019-06-28_15-35-389d8luuxi -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/3 CPUs, 0/0 GPUs
Memory usage on this node: 6.1/8.6 GB
Result logdir: /Users/xiaohongzhi/ray_results/stabilizing_the_ring
RUNNING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	RUNNING

2019-06-28 15:35:47,977	WARNING ppo.py:137 -- By default, observations will be normalized with MeanStdFilter
Loading configuration... done.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/types_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/nodes_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/edges_file.xsd', will try website lookup.
Success.
 Starting SUMO on port 51625
Loading configuration... done.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/routes_file.xsd', will try website lookup.
2019-06-28 15:36:12,580	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-06-28 15:36:12.583976: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-06-28 15:36:14,292	INFO multi_gpu_optimizer.py:74 -- LocalMultiGPUOptimizer devices ['/cpu:0']
Loading configuration... Loading configuration... done.
done.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/types_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/types_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/nodes_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/nodes_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/edges_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/edges_file.xsd', will try website lookup.
Success.
Success.
 Starting SUMO on port 51671
 Starting SUMO on port 51670
Loading configuration... done.
Loading configuration... done.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/routes_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/routes_file.xsd', will try website lookup.
2019-06-28 15:36:49,550	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 1 on CPU (please ignore any CUDA init errors)
2019-06-28 15:36:49.551956: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-06-28 15:36:49,719	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 2 on CPU (please ignore any CUDA init errors)
2019-06-28 15:36:49.721394: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
(flow) wlan-napt-003:flow xiaohongzhi$ python examples/rllib/stabilizing_the_ring.py
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-28_15-35-37_73338/logs.
Waiting for redis server at 127.0.0.1:11257 to respond...
Waiting for redis server at 127.0.0.1:27753 to respond...
Starting the Plasma object store with 3.435973836 GB memory using /tmp.
I0628 15:35:38.073626 222512576 store.cc:994] Allowing the Plasma store to use up to 3.43597GB of memory.
I0628 15:35:38.076272 222512576 store.cc:1024] Starting object store with directory /tmp and huge page support disabled
Failed to start the UI, you may need to run 'pip install jupyter'.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 6.1/8.6 GB

Created LogSyncer for /Users/xiaohongzhi/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2019-06-28_15-35-389d8luuxi -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/3 CPUs, 0/0 GP/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

-----------------------
ring length: 235
v_max: 3.9514850725282584
-----------------------

-----------------------
ring length: 264
v_max: 5.329679917416892
-----------------------
Loading configuration... Loading configuration... done.
done.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/types_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/types_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/nodes_file.xsd', will try website lookup.
Warning: Cannot read local schema '/Users/xiaohongzhi/sumo_binaries/bin/data/xsd/nodes_file.xsd', will try website lookup.



I really need to use flow to finish my graduate project, but the installing procedure for me is too difficult, i already faced many problems, but never fixed.....
Please help me, dear you.
I will appreciate your kindness.

**Comment by xiaoToby** [comment]
Ok, on your website, there is another way to install sumo. - (Optional) Direct install of SUMO from GitHub

I tried it. And then i check sumo_binaries/bin, there is no file here. ....

The log is : 
(flow) wlan-napt-003:flow xiaohongzhi$ cd ~
(flow) wlan-napt-003:~ xiaohongzhi$ git clone https://github.com/eclipse/sumo.git
fatal: destination path 'sumo' already exists and is not an empty directory.
(flow) wlan-napt-003:~ xiaohongzhi$ cd sumo
(flow) wlan-napt-003:sumo xiaohongzhi$ git checkout 2147d155b1
HEAD is now at 2147d155b1 version info for cmake, refs #563
(flow) wlan-napt-003:sumo xiaohongzhi$ make -f Makefile.cvs
autoreconf -i
glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
glibtoolize: and rerunning glibtoolize and aclocal.
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
glibtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
(flow) wlan-napt-003:sumo xiaohongzhi$ brew update
Already up-to-date.
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install Caskroom/cask/xquartz
==> brew cask install Caskroom/cask/xquartz 
Warning: Cask 'xquartz' is already installed.

To re-install xquartz, run:
  brew cask reinstall xquartz
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install autoconf
Warning: autoconf 2.69 is already installed and up-to-date
To reinstall 2.69, run `brew reinstall autoconf`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install automake
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install pkg-config
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install libtool
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install gdal
Warning: gdal 2.4.1_1 is already installed and up-to-date
To reinstall 2.4.1_1, run `brew reinstall gdal`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install proj
Warning: proj 6.1.0 is already installed and up-to-date
To reinstall 6.1.0, run `brew reinstall proj`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install xerces-c
Warning: xerces-c 3.2.2 is already installed and up-to-date
To reinstall 3.2.2, run `brew reinstall xerces-c`
(flow) wlan-napt-003:sumo xiaohongzhi$ brew install fox
Warning: fox 1.6.56_1 is already installed and up-to-date
To reinstall 1.6.56_1, run `brew reinstall fox`
(flow) wlan-napt-003:sumo xiaohongzhi$ export CPPFLAGS=-I/opt/X11/include
(flow) wlan-napt-003:sumo xiaohongzhi$ export LDFLAGS=-L/opt/X11/lib
(flow) wlan-napt-003:sumo xiaohongzhi$ ./configure CXX=clang++ CXXFLAGS="-stdlib=libc++ -std=gnu++11" --with-xerces=/usr/local --with-proj-gdal=/usr/local
checking build system type... x86_64-apple-darwin18.6.0
checking host system type... x86_64-apple-darwin18.6.0
checking target system type... x86_64-apple-darwin18.6.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking dependency style of clang++... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.6.0 file names to x86_64-apple-darwin18.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.6.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... clang++ -E
checking for ld used by clang++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the clang++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for clang++ option to produce PIC... -fno-common -DPIC
checking if clang++ PIC flag -fno-common -DPIC works... yes
checking if clang++ static flag -static works... no
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for xerces-c >= 3.0... yes
checking for main in -lxerces-c... yes
checking xercesc/util/XercesVersion.hpp usability... yes
checking xercesc/util/XercesVersion.hpp presence... yes
checking for xercesc/util/XercesVersion.hpp... yes
checking for main in -lproj... yes
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj-includes not found in "/usr/local/include".
(flow) wlan-napt-003:sumo xiaohongzhi$ make -j$nproc
make: *** No targets specified and no makefile found.  Stop.
(flow) wlan-napt-003:sumo xiaohongzhi$ echo 'export SUMO_HOME="$HOME/sumo"' >> ~/.bash_profile
(flow) wlan-napt-003:sumo xiaohongzhi$ echo 'export PATH="$HOME/sumo/bin:$PATH"' >> ~/.bash_profile
(flow) wlan-napt-003:sumo xiaohongzhi$ echo 'export PYTHONPATH="$HOME/sumo/tools:$PYTHONPATH"' >> ~/.bash_profile
(flow) wlan-napt-003:sumo xiaohongzhi$ source ~/.bash_profile
(base) wlan-napt-003:sumo xiaohongzhi$ echo $PATH
/Users/xiaohongzhi/sumo/bin:/anaconda3/bin:/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/xiaohongzhi/sumo/bin:/Users/xiaohongzhi/sumo/bin:/Users/xiaohongzhi/sumo_binaries/bin
(base) wlan-napt-003:sumo xiaohongzhi$ cd ~
(base) wlan-napt-003:~ xiaohongzhi$ cd sumo_binaries/bin
(base) wlan-napt-003:bin xiaohongzhi$ ls
(base) wlan-napt-003:bin xiaohongzhi$ ls -l


I really want one kind people to help fix my problems.
Help!!!!

**Comment by nathanlct** [comment]
Hello @xiaoToby,

Your first issue looks similar to the one we have already answered [here on stackoverflow](https://stackoverflow.com/questions/56786954/failed-to-install-sumo-binaries). Can you see if that works for you? 

Regarding your problem with running the `aimsun/sugiyama.py` example, we are aware of this bug and it is fixed in #565. You can pull the `aimsun_bug` branch if you need to be able to run this example soon, otherwise the pull request should be merged into `master` soon.

As for running the `rllib/stabilizing_the_ring.py` example, what error do you get? I can only see warnings.

Let us know if you encounter other issues!

**Comment by xiaoToby** [comment]
Thanks for your helping.

I still have a question, the aimsun is not free, right? 
If i want to use it normally run your programs, i need to pay.

About rllib/stabilizing_the_ring.py , I realize my problem, i need to change render=True.

Thanks.

**Comment by nathanlct** [comment]
Indeed, you need to buy a license in order to use Aimsun, or you can get a one month free trial.

However most of our experiments use Sumo/Traci so just ignore the Aimsun part and you should be fine!

As for the `rllib/stabilizing_the_ring.py` example, render is set by default set to False as it makes the training process much faster. 
You can however train an agent without rendering it, and then render the result. To do this, you can have a look at the visualizers tutorial.

I hope this helps, and feel free to close this issue!

In the future, please post your questions on StackOveflow using the `flow-project` tag if you need more help, since we are from now on reserving the Github issues for reports of bugs in the codebase.
